# Generated by Django 2.0.6 on 2018-06-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.TextField(default=''),
        ),
    ]
